### ISSUE TITLE
Send logs to /dev/pmsg0

### ISSUE THREAD

**Issue by flxo** [flxo/android-logd-logger#6]
The logger shall write the logs in addition to logd to `/dev/pmsg0` - a userspace pstore object that is persistent across reboots.

See https://cs.android.com/android/platform/superproject/+/master:system/logging/liblog/pmsg_writer.cpp

**Comment by sgasse** [comment]
I think this can be closed since the merge of #8

**Comment by flxo** [comment]
Fixed by #8
